// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://japdgdcpgxtlzejrqxfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphcGRnZGNwZ3h0bHplanJxeGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTQ4MzYsImV4cCI6MjA2Mjk5MDgzNn0.1aCysxEAG7ul0W33KfP89jcM8xR8eIOT6TQR3V-Exjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);